---
name: "Libre.fm"
guid: "b78cf106-4cf0-4147-807a-1846f8745f19"
version: "10.11.0.5"
targetAbi: "10.11.0.5"
framework: "net9.0"
overview: "A plugin that scrobbles your Jellyfin music to Libre.fm"
description: >
  Scrobble Libre.fm plays with Jellyfin.
category: "Music"
owner: "moisespr123"
artifacts:
  - "Jellyfin.Plugin.Libre.dll"
changelog: >
  Manifest tools updated to danielfariati/jellyfin-utilities
